### ISSUE TITLE
Convert functions not available in Laravel 5.2

### ISSUE THREAD

**Issue by GustavsR** [camroncade/timezone#14]
Title says it all - convert functions are not available globally in L5.2.

Controller method - 
`public function index()
{
    return convertFromUTC(Carbon::now(), 'Europe/Riga');
}`

Error I get - 
`FatalThrowableError in SettingsController.php line 26:
Call to undefined function MyApp\Http\Controllers\Client\convertFromUTC()`

**Comment by camroncade** [comment]
Ah. This is because the functions are not global, but are actually facades on the Timezone class.

So, instead you would call the function like so:
    Timezone::convertFromUTC(Carbon::now(), 'Europe/Riga');

Looking at the readme, I can see now that this wasn't quite clear that this is how it worked. I'll fix it.
