### ISSUE TITLE
timezone list

### ISSUE THREAD

**Issue by luoshiben** [camroncade/timezone#2]
Thanks for the great package. The only problem I'm having is that the list of time zones (and labels with offsets) is hard coded. This means that if the time zone list ever changes a code update is required. Also, the offsets for zones that use DST will only be correct half of the year. Relating to this, if I get a list of timezones according to php (using timezone_abbreviations_list(), for example), it shows that "America/Denver" is used for my area, but your hard coded list has "US/Mountain". Because I'm relying on PHP timezones, my values don't always match those returned by your package. It might be nice to instead generate the list of timezones dynamically to avoid these problems.

If useful, something like this could be used, though it doesn't generate the "pretty" names you have now!
```PHP
public function getTimeZoneList($region=DateTimeZone::ALL, $country=null) {
		$zonesArray = array();
		$timestamp = time();
		$tzList = timezone_identifiers_list($region, $country);

		foreach($tzList as $key => $zone) {
			date_default_timezone_set($zone);
			$label = '(UTC' . date('P', $timestamp) . ') ' . str_replace('_',' ',$zone);
			$zonesArray[$label] = $zone;
		}
		ksort($zonesArray);

		return $zonesArray;
}
```

**Comment by camroncade** [comment]
I'm looking into this, you bring up a good point.

Calling `timezone_identifies_list()` return 417 different timezones, many of which share the same offset, which just seems to me to be redundant, as opposed to this hard-coded list of 142. 

Maybe we abstract the actual timezone list out of the code, using the one already included by default. Then someone could provide a list generated from a method similar to the one you suggested above.

I don't know. Timezones in PHP seem a bit gimmicky to me and I'm not really sure what the best way of going about this is. I'm definitely open to suggestions.
