### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by xtCat** [camroncade/timezone#4]
This package is throwing a error in laravel 5:

BadMethodCallException in ServiceProvider.php line 226: Call to undefined method [package]

**Comment by dennisoderwald** [comment]
+1

**Comment by camroncade** [comment]
Sorry it took so long to get back to you on this. 

I found the problem in TimezoneServiceProvider, it was calling the old package registration method from Laravel 4. This is the problematic line:

```php
$this->package('camroncade/timezone');
```
Removing this line seems to fix the issue at hand. I'll have the fix pushed to the Github repository later this evening. Thanks.
